- twitter4j-async/src/main/java/twitter4j/AsyncTwitterImpl.java
- twitter4j-async/src/main/java/twitter4j/auth/AsyncOAuthSupport.java
- twitter4j-core/src/main/java/twitter4j/TwitterBaseImpl.java
- twitter4j-core/src/main/java/twitter4j/auth/OAuthAuthorization.java
- twitter4j-core/src/main/java/twitter4j/auth/OAuthSupport.java
The reverse auth process needs a special request token, see https://dev.twitter.com/docs/ios/using-reverse-auth#step-1-obtain-a-special-request-token
To get a special request token a new `x_auth_mode` parameter is used for the request to `https://api.twitter.com/oauth/request_token`.
Example usage:
```java
Twitter twitter = new TwitterFactory().getInstance();
twitter.setOAuthConsumer(consumerKey, consumerSecret);
RequestToken rt = twitter.getOAuthRequestToken(null, null, "reverse_auth");
```
You can make the request to `/oauth/request_token` server side and then send `rt` to your client to get an access token to share with your server.
See also discussion at https://groups.google.com/d/msg/twitter4j/7Gtb798nI-k/XjO4S9q7O-8J
> Add xAuthMode param to getOAuthRequestToken to support reverse auth

- twitter4j-core/src/main/java/twitter4j/api/ListsResources.java
Lists can now have up to 5000 members, where before this was only 500.
https://support.twitter.com/articles/20169276-i-m-having-trouble-with-lists
> Update JavaDoc with correct people limit in lists.

- twitter4j-core/src/internal-http/java/twitter4j/HttpParameter.java
- twitter4j-core/src/main/java/twitter4j/Query.java
- twitter4j-core/src/test/java/twitter4j/SearchAPITest.java
First, thanks for building and maintaining twitter4j for so long. It's a pleasure to use! :)
My team recently tried to do some simple status searching, and we noticed that while paging status searches is easy, the "next page" fields are not exposed by the current API. (They're handled opaquely by the `Query` object using a anextPagea query parameters variable.)
This change parses those `nextPage` variables and extracts the values from that parameter string into the greater `Query` object whenever possible, namely:
* `query`
* `lang`
* `locale`
* `max_id`
* `count`
* `geocode`
* `result_type`
Other variables -- `since`, `until`, and `since_id` -- get rolled into the query (e.g., `since:2014-1-1`) and so are not parsed into the `Query`.
This change is fully backwards compatible. This change …
> Status search parameter parsing

- twitter4j-core/src/test/java/twitter4j/TwitterTestBase.java
> Fixed the omission which was happened when converting user_id from int to long.

- twitter4j-stream/src/main/java/twitter4j/StreamController.java
When a sitestream is shut down the onClose event calls the StreamController.setControlURI with a null. This causes an npe error in the stream controller where it is assumed that the method will always be called with a valid string.
> Protect from npe when invoking shutdown on site stream

- readme.txt
- twitter4j-core/src/main/java/twitter4j/TwitterImpl.java
- twitter4j-core/src/main/java/twitter4j/api/ListsResources.java
http://issue.twitter4j.org/youtrack/issue/TFJ-871
reverse parameter for : https://dev.twitter.com/rest/reference/get/lists/list
count parameter for https://dev.twitter.com/rest/reference/get/lists/memberships
count & skip_status parameters for https://dev.twitter.com/rest/reference/get/lists/subscribers
count & skip_status parameters for https://dev.twitter.com/rest/reference/get/lists/members
count & user_id parameters for https://dev.twitter.com/rest/reference/get/lists/subscriptions
include_entities parameter not included, "will be made a default component of output in the future"
make "count" optional for getUserListsOwnerships https://dev.twitter.com/rest/reference/get/lists/ownerships
> TFJ-871 Support for extra ListsResources Parameters

- readme.txt
- twitter4j-core/src/main/java/twitter4j/TwitterBaseImpl.java
Hi.
When no twitter4j.properties file and haven't registered yet, I was very hard searching for this page.
So, I think this error message should have the link for register page for developers.
http://apps.twitter.com/
> Add error message when no twitter4j.properties file

- twitter4j-core/src/internal-http/java/twitter4j/HttpClientFactory.java
`HttpClientFactory` is using a `HashMap` for storing an `HttpClient` instance per `HttpClientConfiguration`.
When multiple threads are invoking `HttpClientFactory.getInstance()`, some may run into an infinite loop (see [JDK-7027300](http://bugs.java.com/view_bug.do?bug_id=7027300)).
Using a `ConcurrentHashMap` solves the issue.
Example stack trace:
```
"thread-2" prio=10 tid=0x00007fe2a0e53000 nid=0x2db3 runnable [0x00007fe22f1ef000]
java.lang.Thread.State: RUNNABLE
at java.util.HashMap.getEntry(HashMap.java:465)
at java.util.HashMap.get(HashMap.java:417)
at twitter4j.HttpClientFactory.getInstance(HttpClientFactory.java:70)
at twitter4j.auth.OAuthAuthorization.<init>(OAuthAuthorization.java:56)
at twitter4j.TwitterFactory.getInstance(TwitterFactory.java:143)
...
"thread-1" prio=10 …
```
> Fix thread sync bug in HttpClientFactory

- twitter4j-appengine/src/main/java/twitter4j/LazyUser.java
- twitter4j-core/src/internal-json/java/twitter4j/UserJSONImpl.java
- twitter4j-core/src/main/java/twitter4j/TwitterBaseImpl.java
- twitter4j-core/src/main/java/twitter4j/TwitterImpl.java
- twitter4j-core/src/main/java/twitter4j/User.java
- twitter4j-core/src/main/java/twitter4j/api/UsersResources.java
As per their documentation, Twitter started to include the user email on the verify request endpoint.
https://dev.twitter.com/rest/reference/get/account/verify_credentials
This PR includes a way for the library users to send parameters to the verify_credentials endpoint to request the user email
> Adding email support

- twitter4j-appengine/src/main/java/twitter4j/LazyUser.java
- twitter4j-core/src/internal-json/java/twitter4j/ParseUtil.java
- twitter4j-core/src/internal-json/java/twitter4j/UserJSONImpl.java
- twitter4j-core/src/main/java/twitter4j/TwitterBaseImpl.java
- twitter4j-core/src/main/java/twitter4j/User.java
- twitter4j-core/src/main/java/twitter4j/conf/Configuration.java
- twitter4j-core/src/main/java/twitter4j/conf/ConfigurationBase.java
- twitter4j-core/src/main/java/twitter4j/conf/ConfigurationBuilder.java
- twitter4j-core/src/main/java/twitter4j/conf/PropertyConfiguration.java
I propose a better approach than #220 for getting the email address of a Twitter user using the Twitter REST API endpoint [_GET account/verify_credentials_](https://dev.twitter.com/rest/reference/get/account/verify_credentials)
Because requesting a user's email address requires that Twitter whitelists the application the user signs into I made the inclusion of the include_email parameter configurable through either:
1. twitter4j.properties file, by setting the includeEmail property to true
2. ConfigurationBuilder , by calling the setIncludeEmailEnabled(true) method on it
```java
ConfigurationBuilder builder = new ConfigurationBuilder();
builder.setOAuthConsumerKey(cKey);
builder.setOAuthConsumerSecret(cSecret);
builder.setOAuthAccessToken(accessToken.getToken()); …
```
> Add support for getting email address from Twitter user

- twitter4j-core/src/internal-json/java/twitter4j/LanguageJSONImpl.java
- twitter4j-core/src/internal-json/java/twitter4j/ScopesImpl.java
- twitter4j-core/src/main/java/twitter4j/api/HelpResources.java
This patch ensures that all *Impl classes under internal-json are Serializable.
Some classes referenced by Status not being Serializable was causing NotSerializableException when trying to serialize certain statuses.
I have not checked for the existence of other classes that are unserializable when they should be.
> Makes all implementation classes Serializable

- twitter4j-core/src/main/java/twitter4j/TwitterBaseImpl.java
- twitter4j-stream/src/main/java/twitter4j/TwitterStream.java
- twitter4j-stream/src/main/java/twitter4j/TwitterStreamImpl.java
Hi,
We are using twitter4j for an Sparsity-Technologies application. We have considered useful to monitorize which are the active streamings assigning a name to the related thread because we have a thread per user. 
We have attached also a minor change to work with Java 6. We would be grateful if you add our changes into the future deployed version. 
Thank you in advance
> Some useful changes to monitorize streams

- twitter4j-core/src/internal-json/java/twitter4j/StatusJSONImpl.java
The two identical chunks of code originate from separate commits. Maybe some kind of merge hazard has included both?
Surely doing the same work again won't break anything but it looks wasteful.
> Remove seemingly unnecessary double work

- twitter4j-core/src/internal-json/java/twitter4j/URLEntityJSONImpl.java
Fix missing "url" param on DM user object
> Fix missing "url"

- readme.txt
- twitter4j-core/src/internal-json/java/twitter4j/TrendJSONImpl.java
- twitter4j-core/src/main/java/twitter4j/Trend.java
Adds support for the `tweet_volume` field of `/trends/place` API response. Refer to the [Twitter API Documentation](https://dev.twitter.com/rest/reference/get/trends/place) for more information.
> Resolves TFJ-886 - Adds tweetVolume field to Trend

- twitter4j-stream/src/main/java/twitter4j/StreamListener.java
To fix java.lang.IllegalAccessError on other JVMs [see](https://stackoverflow.com/questions/45781964/how-to-make-kotlin-stop-casting-argument-to-wrong-classinterface)
> fix: make StreamListener public

- readme.txt
- twitter4j-appengine/src/main/java/twitter4j/LazyUser.java
- twitter4j-core/src/internal-json/java/twitter4j/UserJSONImpl.java
- twitter4j-core/src/main/java/twitter4j/User.java
取得できるprofile_bannerのURLに
300x100
600x200
1500x500
のサイズの追加
> profile_bannerのURLを取得できるサイズの追加

- twitter4j-appengine/src/main/java/twitter4j/LazyUser.java
- twitter4j-core/src/internal-json/java/twitter4j/UserJSONImpl.java
- twitter4j-core/src/main/java/twitter4j/User.java
It seems that "_400x400" has been used as the URL of the profile image so add it.
----
プロフィール画像の URL として _400x400 が使われるようになったようなのでそれを取得できるようにしました。
> add 400x400 size of profile image

- readme.txt
- twitter4j-core/src/main/java/twitter4j/Query.java
Query class was missing the geoCode method with the new signature with Unit and the old geoCode and setGeoCode were referencing to use the Unit parameter instead of String.
Added deprecation to old geoCode method with String parameter.
> added missing geoCode method and doc fixes

- powered-by-badge/readme.txt
- twitter4j-async/src/test/java/twitter4j/AsyncTwitterTest.java
- twitter4j-core/src/main/java/twitter4j/TwitterResponse.java
- twitter4j-core/src/main/java/twitter4j/api/FriendsFollowersResources.java
- twitter4j-core/src/main/java/twitter4j/api/UsersResources.java
- twitter4j-core/src/main/java/twitter4j/conf/ConfigurationFactory.java
- twitter4j-http2-support/src/test/java/twitter4j/Http2ClientTest.java
This pull request fixes the minor typos detected by https://github.com/client9/misspell.
```
$ misspell .
powered-by-badge/readme.txt:1:13: "aplication" is a misspelling of "application"
twitter4j-async/src/test/java/twitter4j/AsyncTwitterTest.java:144:25: "destorying" is a misspelling of "destroying"
twitter4j-core/src/main/java/twitter4j/TwitterResponse.java:20:97: "avaialble" is a misspelling of "available"
twitter4j-core/src/main/java/twitter4j/api/FriendsFollowersResources.java:41:191: "filterd" is a misspelling of "filtered"
twitter4j-core/src/main/java/twitter4j/api/FriendsFollowersResources.java:55:191: "filterd" is a misspelling of "filtered"
twitter4j-core/src/main/java/twitter4j/api/FriendsFollowersResources.java:69:191: "filterd" is a misspelling of "filtered" …
```
> Fix misspelled words in comments

- twitter4j-core/src/internal-http/java/twitter4j/HttpClientConfiguration.java
- twitter4j-core/src/internal-http/java/twitter4j/HttpClientImpl.java
- twitter4j-core/src/main/java/twitter4j/conf/ConfigurationBase.java
- twitter4j-core/src/main/java/twitter4j/conf/ConfigurationBuilder.java
- twitter4j-stream/src/main/java/twitter4j/TwitterStreamImpl.java
Please support Proxy.Type.SOCKS. Here are the changes required.
`HttpClientConfiguration.httpProxySocks` boolean enables SOCKS proxy mode. If false, uses HTTP
proxy when proxy host and port is properly set.
> Added httpProxySocks boolean property to HttpClientConfiguration

- readme.txt
- twitter4j-core/src/internal-json/java/twitter4j/HTMLEntity.java
- twitter4j-core/src/test/java/twitter4j/AllLocalTests.java
- twitter4j-core/src/test/java/twitter4j/HTMLEntityTest.java
The start and end indices of Twitter's entities (e.g. Hashtag entities) are based on code point counts, and not simple single characters like the indexes Java uses for strings.
For example, the Twitter API reports a start index of 9 for the #Maldives hashtag in the following string which contains two supplementary characters:
`NEWS🇧! 🇹 #Maldives`
However, if you want to extract the hashtag using Java's String.substring, you need to use a start index of 11 because Java counts both surrogate characters in the two supplementary characters (each supplementary character contains a high and low surrogate character).  I've therefore modified the `HTMLEntity.unescapeAndSlideEntityIncdices` method to modify the start and end indices of all entities so that they represent the standard Java …
> Use codepoints for entity index sliding

- twitter4j-async/src/main/java/twitter4j/AsyncTwitterImpl.java
I've spent a good while debugging an app using the async API and it would have been a great help if Exceptions weren't just swallowed. This PR at least prints their stack traces to stderr.
> At least print stacktraces instead of swallowing them
