twitter4j-core/src/internal-json/java/twitter4j/MediaEntityJSONImpl.java

Added default constructor to Size class for serialization purposes

Added default constructor to MediaEntity.Size

---

twitter4j-appengine/src/main/java/twitter4j/LazyDirectMessage.java
twitter4j-appengine/src/main/java/twitter4j/LazyStatus.java
twitter4j-core/src/internal-json/java/twitter4j/DirectMessageJSONImpl.java
twitter4j-core/src/internal-json/java/twitter4j/ExtendedMediaEntityJSONImpl.java
twitter4j-core/src/internal-json/java/twitter4j/MediaEntityJSONImpl.java
twitter4j-core/src/internal-json/java/twitter4j/StatusJSONImpl.java
twitter4j-core/src/main/java/twitter4j/EntitySupport.java
twitter4j-core/src/main/java/twitter4j/ExtendedMediaEntity.java
twitter4j-core/src/main/java/twitter4j/MediaEntity.java
twitter4j-core/src/test/java/twitter4j/MediaEntityJSONImplTest.java

see https://twittercommunity.com/t/twitter-video-support-in-rest-and-streaming-api/31258
see https://twittercommunity.com/t/adding-animated-gifs-via-rest-and-streaming-apis/30070

add video support to media entity

---

readme.txt
twitter4j-core/src/main/java/twitter4j/TwitterImpl.java
twitter4j-core/src/main/java/twitter4j/api/TweetsResources.java
twitter4j-core/src/test/java/twitter4j/TweetsResourcesTest.java

Fixes http://issue.twitter4j.org/youtrack/issue/TFJ-860
as discussed here: https://groups.google.com/forum/#!topic/twitter4j/56-kOObbXt0

TFJ-860 Upload Media via InputStream

---

twitter4j-stream/src/main/java/twitter4j/FilterQuery.java

As described [here](https://dev.twitter.com/streaming/overview/request-parameters#filter_level).

TFJ-756: add support for filter_level in Public stream

---

twitter4j-stream/src/main/java/twitter4j/TwitterStream.java
twitter4j-stream/src/main/java/twitter4j/TwitterStreamImpl.java

I feel like one should be able to specify a language for sampling from the public tweet stream.

Adds TwitterStream#sample(String language) to filter the stream by language

---

twitter4j-spdy-support/pom.xml
twitter4j-spdy-support/src/main/java/twitter4j/AlternativeHttpClientImpl.java
twitter4j-spdy-support/src/test/java/twitter4j/SpdyHttpClientTest.java

okhttp2.2 has this bug.
square/okhttp#1305
There is a need to change to okhttp2.3 in order to avoid this bug.

updated to okhttp2.3 and sPreferxxx->public

---

readme.txt
twitter4j-core/src/main/java/twitter4j/TwitterBaseImpl.java
twitter4j-stream/src/main/java/twitter4j/TwitterStreamImpl.java

Fixed missing final for Java7 or older

---

twitter4j-core/src/main/java/twitter4j/TwitterImpl.java
twitter4j-core/src/test/java/twitter4j/FriendsFollowersResourcesTest.java
twitter4j-core/src/test/java/twitter4j/ListResourcesTest.java
twitter4j-core/src/test/java/twitter4j/UsersResourcesTest.java

[TFJ-772](http://issue.twitter4j.org/youtrack/issue/TFJ-772)

Fixed the unauthorized error which is caused by the parameters not encoded

---

twitter4j-appengine/src/main/java/twitter4j/LazySavedSearch.java
twitter4j-core/src/internal-json/java/twitter4j/SavedSearchJSONImpl.java
twitter4j-core/src/main/java/twitter4j/SavedSearch.java
twitter4j-core/src/main/java/twitter4j/TwitterImpl.java
twitter4j-core/src/main/java/twitter4j/api/SavedSearchesResources.java

最近SavedSearchのidが一桁増えたようでintに収まらなくなったのでlongに変更しました。

Changed the id of SavedSearch from int to long

---

twitter4j-core/src/main/java/twitter4j/TwitterFactory.java

Related to TFJ-65, TFJ-380, TFJ-327.

TFJ-882 Remove final from TwitterFactory so that it can be used by Spring dependency injection, or in mock tests.

---

readme.txt
twitter4j-core/src/main/java/twitter4j/api/UsersResources.java

Hi.
I fixed wrong javadoc for twitter.api.UserResources#lookupUsers(long[] ids).
It resolve the issue "TFJ-855".

TFJ-855 Fixed Wrong javadoc

---

library.properties

Updated the version string of this descriptor file for Processing libraries to the current Twitter4J version

Updated the version string to the version of T4J

---

twitter4j-core/src/main/java/twitter4j/Status.java

Hi
When I need client name, I was hard to find client name.
Add example for Status.java from https://dev.twitter.com/rest/reference/get/statuses/show/%3Aid

Add javaDoc comment on Status.java

---

twitter4j-examples/bin/mute/getMutingUsersIDs.cmd
twitter4j-examples/bin/mute/getMutingUsersIDs.sh
twitter4j-examples/src/main/java/twitter4j/examples/mute/GetMutingUsersIDs.java
twitter4j-examples/src/main/java/twitter4j/examples/mute/package-info.java

Hi.
It seems there is no example for getMutingUsersIDs.
So I added example for getMutingUsersIDs with reference to other examples.

add example for getMutingUsersIDs

---

twitter4j-core/src/internal-json/java/twitter4j/ExtendedMediaEntityJSONImpl.java
twitter4j-core/src/main/java/twitter4j/ExtendedMediaEntity.java
twitter4j-core/src/main/java/twitter4j/TwitterImpl.java
twitter4j-core/src/main/java/twitter4j/conf/Configuration.java
twitter4j-core/src/main/java/twitter4j/conf/ConfigurationBase.java
twitter4j-core/src/main/java/twitter4j/conf/ConfigurationBuilder.java
twitter4j-core/src/test/java/twitter4j/MediaEntityJSONImplTest.java

see https://blog.twitter.com/2016/alt-text-support-for-twitter-cards-and-the-rest-api
```java
final ConfigurationBuilder builder = new ConfigurationBuilder();
...
builder.setIncludeExtAltTextEnabled(true);
```
then we can get the alt text of the attached image as below:
```java
status = twitter.showStatus(id);
status.getExtendedMediaEntities()[0].getExtAltText();
```

Support alt text

---

twitter4j-core/src/internal-json/java/twitter4j/TwitterAPIConfigurationJSONImpl.java
twitter4j-core/src/main/java/twitter4j/TwitterAPIConfiguration.java

Please confirm this page: https://dev.twitter.com/rest/reference/get/help/configuration

Add parameter dm_text_character_limit to TwitterAPIConfiguration

---

twitter4j-core/src/internal-json/java/twitter4j/TrendJSONImpl.java
twitter4j-core/src/main/java/twitter4j/Trend.java

Try the build again.
venilnoronha commented on Oct 19, 2016
Adds support for the tweet_volume field of /trends/place API response. Refer to the Twitter API Documentation for more information.

Resolves TFJ-886 - Adds tweetVolume field to Trend #251

---

twitter4j-core/src/main/java/twitter4j/TwitterImpl.java
twitter4j-core/src/main/java/twitter4j/api/TweetsResources.java
twitter4j-core/src/test/java/twitter4j/TweetsResourcesTest.java

adding un-retweet api

---

twitter4j-async/src/main/java/twitter4j/api/TweetsResourcesAsync.java
twitter4j-core/src/main/java/twitter4j/util/CharacterUtil.java
twitter4j-core/src/test/java/twitter4j/util/CharacterUtilTest.java

Twitter official [documentation](https://developer.twitter.com/en/docs/developer-utilities/twitter-text.html)

Support 280 characters per tweet

---

twitter4j-core/src/main/java/twitter4j/EntitySupport.java

Added "return" word in the documentation of all the methods to change "This method will an empty" to "This method will return an empty" in EntitySupport.java.

Updated EntitySupport.java

---

readme.txt
twitter4j-core/src/main/java/twitter4j/GeoQuery.java
twitter4j-core/src/test/java/twitter4j/GeoQueryTest.java

I have just added a new constructor at GeoQuery class which I thought would be good to have. Basically, it is just a generic constructor to pass any of the fields needed to perform a geoquery request against Twitter.

TFJ-887 Added constructor to GeoQuery class

---

twitter4j-core/src/main/java/twitter4j/StatusUpdate.java

add attachment_url parameter for the POST statuses/update endpoint
- [Upcoming changes to Tweets | Twitter Developers](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets)

Support attachment_url

---

twitter4j-core/pom.xml
twitter4j-core/src/internal-logging/java/twitter4j/Log4JLogger.java
twitter4j-core/src/internal-logging/java/twitter4j/Log4JLoggerFactory.java

CVE-2019-17571 - Critical security vulnerability in required log4j version

---

readme-libs.txt

"SPDY / HTTP2.0"  ->  "HTTP2.0"

Remove spdy notation from readme-libs.txt
